server:
  port: 8082

spring:
  application:
    name: redis_service
  data:
    redis:
      host: localhost
      port: 6379
      #      password: redispass
      database: 0
  kafka:
    bootstrap-servers: 192.168.0.106:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: redis-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"